### ISSUE TITLE
1080p开启hidpi的情况下用什么分辨率最好？

### ISSUE THREAD

**Issue by Kosthi** [GatesYang/Magicbook-Pro-16.1-Hackintosh#21]
RT

**Comment by GatesYang** [comment]
大概是16xx开头的那个分辨率，好久没开都忘记咯

**Comment by Kosthi** [comment]
> 大概是16xx开头的那个分辨率，好久没开都忘记咯

<img width="780" alt="截屏2020-03-31 14 27 13" src="https://user-images.githubusercontent.com/30976463/77994031-e3d7a480-735b-11ea-947d-8b4875a4874c.png">

**Comment by GatesYang** [comment]
> > 大概是16xx开头的那个分辨率，好久没开都忘记咯
> 
> <img alt="截屏2020-03-31 14 27 13" width="780" src="https://user-images.githubusercontent.com/30976463/77994031-e3d7a480-735b-11ea-947d-8b4875a4874c.png">

没错就是这个
