### ISSUE TITLE
关于magicbook2019显卡问题

### ISSUE THREAD

**Issue by 1Huang1** [GatesYang/Magicbook-Pro-16.1-Hackintosh#3]
大佬，想问一下关于magicbook2019的显卡怎么操作，因为上到i58265和mx250跟2018版不一样，跟pro一样，原efi用着会没有背光或者屏幕太暗调不了亮度，大佬能不能教一下这方面怎么操作

**Comment by GatesYang** [comment]
你先看看显卡是不是正确驱动了，现在i5 8265的UHD620貌似没有完美支持，我调试pro的时候也是遇到这种情况，试试用hackintool注入一个驱动

**Comment by 1Huang1** [comment]
用了仿冒显卡630的教程，发现的问题,mac亮度最高是win的最低亮度，设备显示的是630的错误显示，不知道怎么修改发自我的iPhone------------------ 原始邮件 ------------------发件人: Gates Yang  <notifications@github.com>发送时间: 2019年11月13日 02:18收件人: GatesYang/Magicbook-Pro-16.1-Hackintosh <Magicbook-Pro-16.1-Hackintosh@noreply.github.com>抄送: 1Huang1 <78487861qq@gmail.com>, Author <author@noreply.github.com>主题: 回复：[GatesYang/Magicbook-Pro-16.1-Hackintosh] 关于magicbook2019显卡问题 (#3)你先看看显卡是不是正确驱动了，现在i5 8265的UHD620貌似没有完美支持，我调试pro的时候也是遇到这种情况，试试用hackintool注入一个驱动

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/GatesYang/Magicbook-Pro-16.1-Hackintosh/issues/3?email_source=notifications\u0026email_token=ANYFKZAPY73F2M6O5TFCW4TQTNPVVA5CNFSM4JMN5N6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOED4UIOA#issuecomment-553206840",
"url": "https://github.com/GatesYang/Magicbook-Pro-16.1-Hackintosh/issues/3?email_source=notifications\u0026email_token=ANYFKZAPY73F2M6O5TFCW4TQTNPVVA5CNFSM4JMN5N6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOED4UIOA#issuecomment-553206840",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by GatesYang** [comment]
是这样的，如果用黑果小兵建议的UHD620的那个ID，驱动出来的是不完美的，我忘记我用的是5916000还是哪个了，但是我记得是十代平台的，Iris655?虽然仿冒的不是UHD620，但是Hackintool打上补丁就会显示UHD620而且是正常使用的，我估计是8265的UHD620有一点不一样？

**Comment by 1Huang1** [comment]
> 是这样的，如果用黑果小兵建议的UHD620的那个ID，驱动出来的是不完美的，我忘记我用的是5916000还是哪个了，但是我记得是十代平台的，Iris655?虽然仿冒的不是UHD620，但是Hackintool打上补丁就会显示UHD620而且是正常使用的，我估计是8265的UHD620有一点不一样？

好的，我先试试，不过可能还有些问题要麻烦老哥，新手小白太多不会

**Comment by GatesYang** [comment]
哈哈我也是小白，多尝试就OK咯

**Comment by 1Huang1** [comment]
> 哈哈我也是小白，多尝试就OK咯

大佬，想问一下magicbook2019换1820a根本不识别能不能说明这台电脑只支持cnvi协议

**Comment by GatesYang** [comment]
> > 哈哈我也是小白，多尝试就OK咯
> 
> 大佬，想问一下magicbook2019换1820a根本不识别能不能说明这台电脑只支持cnvi协议

估计是的，好像magicbook的主板BIOS没有开放支持非CNVI网卡的选项，我在论坛看到有人说隔壁联想有这个功能，说明理论可行，只是厂商没有做，需要更多的人把这个情况反馈到荣耀官方那边可能会有机会开放这个功能

**Comment by 1Huang1** [comment]
> > > 哈哈我也是小白，多尝试就OK咯
> > 
> > 
> > 大佬，想问一下magicbook2019换1820a根本不识别能不能说明这台电脑只支持cnvi协议
> 
> 估计是的，好像magicbook的主板BIOS没有开放支持非CNVI网卡的选项，我在论坛看到有人说隔壁联想有这个功能，说明理论可行，只是厂商没有做，需要更多的人把这个情况反馈到荣耀官方那边可能会有机会开放这个功能

那我想问一下这种情况和华为matebook换不了网卡的情况是一样的吗？

**Comment by GatesYang** [comment]
> > > > 哈哈我也是小白，多尝试就OK咯
> > > 
> > > 
> > > 大佬，想问一下magicbook2019换1820a根本不识别能不能说明这台电脑只支持cnvi协议
> > 
> > 
> > 估计是的，好像magicbook的主板BIOS没有开放支持非CNVI网卡的选项，我在论坛看到有人说隔壁联想有这个功能，说明理论可行，只是厂商没有做，需要更多的人把这个情况反馈到荣耀官方那边可能会有机会开放这个功能
> 
> 那我想问一下这种情况和华为matebook换不了网卡的情况是一样的吗？

我认为是一样的...但真实情况还得懂这方面的大佬说话

**Comment by 1Huang1** [comment]
> > > > > 哈哈我也是小白，多尝试就OK咯
> > > > 
> > > > 
> > > > 大佬，想问一下magicbook2019换1820a根本不识别能不能说明这台电脑只支持cnvi协议
> > > 
> > > 
> > > 估计是的，好像magicbook的主板BIOS没有开放支持非CNVI网卡的选项，我在论坛看到有人说隔壁联想有这个功能，说明理论可行，只是厂商没有做，需要更多的人把这个情况反馈到荣耀官方那边可能会有机会开放这个功能
> > 
> > 
> > 那我想问一下这种情况和华为matebook换不了网卡的情况是一样的吗？
> 
> 我认为是一样的...但真实情况还得懂这方面的大佬说话

老哥有试过用在pro吗？因为论坛上有人2019款换了ax200和9260这俩都不是cnvi协议

**Comment by AlikWu** [comment]
> > > > > > 哈哈我也是小白，多尝试就OK咯
> > > > > 
> > > > > 
> > > > > 大佬，想问一下magicbook2019换1820a根本不识别能不能说明这台电脑只支持cnvi协议
> > > > 
> > > > 
> > > > 估计是的，好像magicbook的主板BIOS没有开放支持非CNVI网卡的选项，我在论坛看到有人说隔壁联想有这个功能，说明理论可行，只是厂商没有做，需要更多的人把这个情况反馈到荣耀官方那边可能会有机会开放这个功能
> > > 
> > > 
> > > 那我想问一下这种情况和华为matebook换不了网卡的情况是一样的吗？
> > 
> > 
> > 我认为是一样的...但真实情况还得懂这方面的大佬说话
> 
> 老哥有试过用在pro吗？因为论坛上有人2019款换了ax200和9260这俩都不是cnvi协议



> > > > > > 哈哈我也是小白，多尝试就OK咯
> > > > > 
> > > > > 
> > > > > 大佬，想问一下magicbook2019换1820a根本不识别能不能说明这台电脑只支持cnvi协议
> > > > 
> > > > 
> > > > 估计是的，好像magicbook的主板BIOS没有开放支持非CNVI网卡的选项，我在论坛看到有人说隔壁联想有这个功能，说明理论可行，只是厂商没有做，需要更多的人把这个情况反馈到荣耀官方那边可能会有机会开放这个功能
> > > 
> > > 
> > > 那我想问一下这种情况和华为matebook换不了网卡的情况是一样的吗？
> > 
> > 
> > 我认为是一样的...但真实情况还得懂这方面的大佬说话
> 
> 老哥有试过用在pro吗？因为论坛上有人2019款换了ax200和9260这俩都不是cnvi协议

2019款有人换了 ax200和9260 ？你有论坛地址吗？我去看看。我试着在我的 MagicBook Pro 上更换了    DW1560 和 DW1820A ，均为不识别该网卡（在设备管理中没有该设备），我在进一步的研究中发现，MagicBook Pro的网卡接口布线是支持非 CNVi 协议网卡的，但是 BIOS 中没有提供切换选项，需要我们向华为和荣耀反馈，添加此选项。这就需要大家一起努力~

**Comment by AlikWu** [comment]
2019款有人换了 ax200和9260 ？你有论坛地址吗？我去看看。我试着在我的 MagicBook Pro 上更换了 DW1560 和 DW1820A ，均为不识别该网卡（在设备管理中没有该设备），我在进一步的研究中发现，MagicBook Pro的网卡接口布线是支持非 CNVi 协议网卡的，但是 BIOS 中没有提供切换选项，需要我们向华为和荣耀反馈，添加此选项。这就需要大家一起努力~

**Comment by Alecwux** [comment]
> > > > > > 哈哈我也是小白，多尝试就OK咯
> > > > > 
> > > > > 
> > > > > 大佬，想问一下magicbook2019换1820a根本不识别能不能说明这台电脑只支持cnvi协议
> > > > 
> > > > 
> > > > 估计是的，好像magicbook的主板BIOS没有开放支持非CNVI网卡的选项，我在论坛看到有人说隔壁联想有这个功能，说明理论可行，只是厂商没有做，需要更多的人把这个情况反馈到荣耀官方那边可能会有机会开放这个功能
> > > 
> > > 
> > > 那我想问一下这种情况和华为matebook换不了网卡的情况是一样的吗？
> > 
> > 
> > 我认为是一样的...但真实情况还得懂这方面的大佬说话
> 
> 老哥有试过用在pro吗？因为论坛上有人2019款换了ax200和9260这俩都不是cnvi协议

2019款有人换了 ax200和9260 ？你有论坛地址吗？我去看看。我试着在我的 MagicBook Pro 上更换了 DW1560 和 DW1820A ，均为不识别该网卡（在设备管理中没有该设备），我在进一步的研究中发现，MagicBook Pro的网卡接口布线是支持非 CNVi 协议网卡的，但是 BIOS 中没有提供切换选项，需要我们向华为和荣耀反馈，添加此选项。这就需要大家一起努力~

**Comment by 1Huang1** [comment]
> > > > > > > 哈哈我也是小白，多尝试就OK咯
> > > > > > 
> > > > > > 
> > > > > > 大佬，想问一下magicbook2019换1820a根本不识别能不能说明这台电脑只支持cnvi协议
> > > > > 
> > > > > 
> > > > > 估计是的，好像magicbook的主板BIOS没有开放支持非CNVI网卡的选项，我在论坛看到有人说隔壁联想有这个功能，说明理论可行，只是厂商没有做，需要更多的人把这个情况反馈到荣耀官方那边可能会有机会开放这个功能
> > > > 
> > > > 
> > > > 那我想问一下这种情况和华为matebook换不了网卡的情况是一样的吗？
> > > 
> > > 
> > > 我认为是一样的...但真实情况还得懂这方面的大佬说话
> > 
> > 
> > 老哥有试过用在pro吗？因为论坛上有人2019款换了ax200和9260这俩都不是cnvi协议
> 
> 2019款有人换了 ax200和9260 ？你有论坛地址吗？我去看看。我试着在我的 MagicBook Pro 上更换了 DW1560 和 DW1820A ，均为不识别该网卡（在设备管理中没有该设备），我在进一步的研究中发现，MagicBook Pro的网卡接口布线是支持非 CNVi 协议网卡的，但是 BIOS 中没有提供切换选项，需要我们向华为和荣耀反馈，添加此选项。这就需要大家一起努力~

https://club.huawei.com/thread-21835557-1-1.html和https://cn.ui.vmall.com/thread-20263278-1-2.html

**Comment by GatesYang** [comment]
> https://cn.ui.vmall.com/thread-20263278-1-2.html

2019款的非Pro好像原网卡不是CNVI协议的，但是Pro的9560是CNVI协议的，@AlikWu老哥说的没错，需要反馈，我从京东的客服反馈他居然说这涉及到主板参数的机密，我感觉得跟matebook他们一起反馈，毕竟这个实现起来对主板厂商来说几乎没有技术难度

**Comment by Alecwux** [comment]
> > https://cn.ui.vmall.com/thread-20263278-1-2.html
> 
> 2019款的非Pro好像原网卡不是CNVI协议的，但是Pro的9560是CNVI协议的，@AlikWu老哥说的没错，需要反馈，我从京东的客服反馈他居然说这涉及到主板参数的机密，我感觉得跟matebook他们一起反馈，毕竟这个实现起来对主板厂商来说几乎没有技术难度

是的， 荣耀MagicBook 2019 不一定是 CNVi 协议的网卡，只有 使用了 Intel CPU，且是8.5代U及以上的才能使用CNVi。AMD 或者 Intel 8.5代以下 CPU，才可更换非 CNVi 网卡。我之前 打华为客服电话反馈过，客服的回答是：“目前有这个需求的比较少，以后有需求会考虑的”。所以有需求的最好打电话或者邮件反馈，在论坛里反馈似乎没什么作用。

**Comment by hflyf123** [comment]
> > > https://cn.ui.vmall.com/thread-20263278-1-2.html
> > 
> > 
> > 2019款的非Pro好像原网卡不是CNVI协议的，但是Pro的9560是CNVI协议的，@AlikWu老哥说的没错，需要反馈，我从京东的客服反馈他居然说这涉及到主板参数的机密，我感觉得跟matebook他们一起反馈，毕竟这个实现起来对主板厂商来说几乎没有技术难度
> 
> 是的， 荣耀MagicBook 2019 不一定是 CNVi 协议的网卡，只有 使用了 Intel CPU，且是8.5代U及以上的才能使用CNVi。AMD 或者 Intel 8.5代以下 CPU，才可更换非 CNVi 网卡。我之前 打华为客服电话反馈过，客服的回答是：“目前有这个需求的比较少，以后有需求会考虑的”。所以有需求的最好打电话或者邮件反馈，在论坛里反馈似乎没什么作用。

http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1832832&highlight=8265u
我看远景上有个机械师s1的更换了网卡成功了，看起来就是厂商的问题了

**Comment by 1Huang1** [comment]
> > > > https://cn.ui.vmall.com/thread-20263278-1-2.html
> > > 
> > > 
> > > 2019款的非Pro好像原网卡不是CNVI协议的，但是Pro的9560是CNVI协议的，@AlikWu老哥说的没错，需要反馈，我从京东的客服反馈他居然说这涉及到主板参数的机密，我感觉得跟matebook他们一起反馈，毕竟这个实现起来对主板厂商来说几乎没有技术难度
> > 
> > 
> > 是的， 荣耀MagicBook 2019 不一定是 CNVi 协议的网卡，只有 使用了 Intel CPU，且是8.5代U及以上的才能使用CNVi。AMD 或者 Intel 8.5代以下 CPU，才可更换非 CNVi 网卡。我之前 打华为客服电话反馈过，客服的回答是：“目前有这个需求的比较少，以后有需求会考虑的”。所以有需求的最好打电话或者邮件反馈，在论坛里反馈似乎没什么作用。
> 
> http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1832832&highlight=8265u
> 我看远景上有个机械师s1的更换了网卡成功了，看起来就是厂商的问题了

这也太难受了……有没有破解bios的可能，像联想有个教程就是修改网卡白名单

**Comment by Alecwux** [comment]
> > > > > https://cn.ui.vmall.com/thread-20263278-1-2.html
> > > > 
> > > > 
> > > > 2019款的非Pro好像原网卡不是CNVI协议的，但是Pro的9560是CNVI协议的，@AlikWu老哥说的没错，需要反馈，我从京东的客服反馈他居然说这涉及到主板参数的机密，我感觉得跟matebook他们一起反馈，毕竟这个实现起来对主板厂商来说几乎没有技术难度
> > > 
> > > 
> > > 是的， 荣耀MagicBook 2019 不一定是 CNVi 协议的网卡，只有 使用了 Intel CPU，且是8.5代U及以上的才能使用CNVi。AMD 或者 Intel 8.5代以下 CPU，才可更换非 CNVi 网卡。我之前 打华为客服电话反馈过，客服的回答是：“目前有这个需求的比较少，以后有需求会考虑的”。所以有需求的最好打电话或者邮件反馈，在论坛里反馈似乎没什么作用。
> > 
> > 
> > http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1832832&highlight=8265u
> > 我看远景上有个机械师s1的更换了网卡成功了，看起来就是厂商的问题了
> 
> 这也太难受了……有没有破解bios的可能，像联想有个教程就是修改网卡白名单

我没有找到 机械师S1 这款机器，有款 机械革命S1 Pro 不知是不是那位楼主的电脑。
根据网上对  机械革命S1 Pro 的拆解评测 ，可以发现其原网卡 9560AC 是 焊接式，不是M.2插槽式的，（例如：https://post.smzdm.com/p/aoo6zv57/  这个拆解）。如果更换，应该是通过转换卡用了固态的位置之类的，具体的也就不清楚了

**Comment by Alecwux** [comment]
> > > > > > https://cn.ui.vmall.com/thread-20263278-1-2.html
> > > > > 
> > > > > 
> > > > > 2019款的非Pro好像原网卡不是CNVI协议的，但是Pro的9560是CNVI协议的，@AlikWu老哥说的没错，需要反馈，我从京东的客服反馈他居然说这涉及到主板参数的机密，我感觉得跟matebook他们一起反馈，毕竟这个实现起来对主板厂商来说几乎没有技术难度
> > > > 
> > > > 
> > > > 是的， 荣耀MagicBook 2019 不一定是 CNVi 协议的网卡，只有 使用了 Intel CPU，且是8.5代U及以上的才能使用CNVi。AMD 或者 Intel 8.5代以下 CPU，才可更换非 CNVi 网卡。我之前 打华为客服电话反馈过，客服的回答是：“目前有这个需求的比较少，以后有需求会考虑的”。所以有需求的最好打电话或者邮件反馈，在论坛里反馈似乎没什么作用。
> > > 
> > > 
> > > http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1832832&highlight=8265u
> > > 我看远景上有个机械师s1的更换了网卡成功了，看起来就是厂商的问题了
> > 
> > 
> > 这也太难受了……有没有破解bios的可能，像联想有个教程就是修改网卡白名单
> 
> 我没有找到 机械师S1 这款机器，有款 机械革命S1 Pro 不知是不是那位楼主的电脑。
> 根据网上对 机械革命S1 Pro 的拆解评测 ，可以发现其原网卡 9560AC 是 焊接式，不是M.2插槽式的，（例如：https://post.smzdm.com/p/aoo6zv57/ 这个拆解）。如果更换，应该是通过转换卡用了固态的位置之类的，具体的也就不清楚了

很抱歉，由于没有细看，把 14寸的拆解当做了 15寸的，目前没有找到 15寸 机械革命S1 Pro的拆机评测，无法看到具体的情况，还需要进一步了解~
