### ISSUE TITLE
关于magicbookpro16.1的触摸板和网卡问题

### ISSUE THREAD

**Issue by hflyf123** [GatesYang/Magicbook-Pro-16.1-Hackintosh#7]
感谢提供的efi，想问下您使用的是哪款的usb网卡，触摸板的问题是只能使用外接鼠标来解决吗？

**Comment by GatesYang** [comment]
usb网卡是在tb搜“黑苹果usb网卡”，销量最高的那个comfast的；触摸板暂时还编译不好，因为它会连带其它的问题比如电池电量显示，需要等其它大神编译或者等whatevergreen更新后我再重新尝试编译，话说鼠标终究还是比触摸板好用呀，魔法书的触摸板体验和白苹果比肯定有不小的差距的

**Comment by hflyf123** [comment]
> usb网卡是在tb搜“黑苹果usb网卡”，销量最高的那个comfast的；触摸板暂时还编译不好，因为它会连带其它的问题比如电池电量显示，需要等其它大神编译或者等whatevergreen更新后我再重新尝试编译，话说鼠标终究还是比触摸板好用呀，魔法书的触摸板体验和白苹果比肯定有不小的差距的

谢谢

**Comment by hflyf123** [comment]
再次叨扰下，请问下有没有远景论坛的邀请码？有的话麻烦发一个给hflyf123@gmail.com,拜谢。

**Comment by GatesYang** [comment]
> 再次叨扰下，请问下有没有远景论坛的邀请码？有的话麻烦发一个给[hflyf123@gmail.com](mailto:hflyf123@gmail.com),拜谢。

我是在tb买的，十块钱一个，免费的我一直没找到 0.0

**Comment by hflyf123** [comment]
> > 再次叨扰下，请问下有没有远景论坛的邀请码？有的话麻烦发一个给[hflyf123@gmail.com](mailto:hflyf123@gmail.com),拜谢。
> 
> 我是在tb买的，十块钱一个，免费的我一直没找到 0.0

多谢呀

**Comment by hflyf123** [comment]
你好，我用你的efi已经装上了，但是网卡好像没有效果，是要安装什么驱动吗，我也是淘宝买的comfast的

**Comment by GatesYang** [comment]
> 你好，我用你的efi已经装上了，但是网卡好像没有效果，是要安装什么驱动吗，我也是淘宝买的comfast的

哈哈那个你私信tb客服，他会发个驱动给你安装的，记得告诉他是10.15的系统
