### ISSUE TITLE
关盖休眠和手动点击休眠后黑屏

### ISSUE THREAD

**Issue by hflyf123** [GatesYang/Magicbook-Pro-16.1-Hackintosh#9]
合上盖子或者手动点击睡眠后都能进行睡眠，但是唤醒不了，有声音但是屏幕无显示。

**Comment by GatesYang** [comment]
> 合上盖子或者手动点击睡眠后都能进行睡眠，但是唤醒不了，有声音但是屏幕无显示。

试试重新关盖再开盖呢，这个问题我还在研究
